version: "3.7"
services:
  php:
    build:
      args:
        uname: ${PHP_UNAME}
        uid: ${PHP_UID}
        gid: ${PHP_GID}
      context: ./services/php
    container_name: ${PROJECT_NAME}_php
    image: ${PROJECT_NAME}_php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./services/php/php.ini:/usr/local/etc/php/php.ini
      - ../:/var/www
    environment:
      COMPOSER_MEMORY_LIMIT: 3G
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    networks:
      - main_network
    depends_on:
      - db
  #  schedule_worker:
  #    image: ${PROJECT_NAME}_php
  #    restart: unless-stopped
  #    command: php artisan schedule:work
  #    working_dir: /var/www/
  #    volumes:
  #      - ../:/var/www
  #    networks:
  #      - main_network
  #    depends_on:
  #      - php
  db:
    image: mysql:5.7
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    ports:
      - ${DB_LOCAL_PORT}:3306
    volumes:
      - ./services/database/dump:/var/lib/mysql
    networks:
      - main_network

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${NGINX_LOCAL_PORT}:80
    volumes:
      - ../:/var/www
      - ./services/nginx:/etc/nginx/conf.d
    networks:
      - main_network
    depends_on:
      - php
networks:
  main_network:
    driver: bridge
    name: ${PROJECT_NAME}_main_network
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}/${SUBNET_MASK}
