<?php


namespace App\Models;


use App\Models\Query\CustomBuilder;

abstract class Model extends \Illuminate\Database\Eloquent\Model
{
    public function whereIntegerInRaw($column, $values, $boolean = 'and', $not = false)
    {
        return parent::whereIntegerInRaw($column, $values, $boolean, $not); // TODO: Change the autogenerated stub
    }

    protected function newBaseQueryBuilder()
    {
        $connection = $this->getConnection();
        $grammar = $connection->getQueryGrammar();
        $processor = $connection->getPostProcessor();

        return new CustomBuilder($connection, $grammar, $processor);
    }
}
